### ISSUE TITLE
Incomplete elliptic integral returns not fully accurate result

### ISSUE THREAD

**Issue by kagalenko-m-b** [stla/EllipticFunctions.jl#9] opened 2022-10-26 09:44 UTC
```
using EllipticFunctions,QuadGK
setprecision(512);
phi=big"0.15";m=big"0.81";
I=ellipticF(phi,m);
I0=quadgk(t->1/sqrt(1-m*sin(t)^2), 0, phi);
println("EllipticFunctions error: ", Float64(I-I0[1]))
println("Estimated quadratue error: ", Float64(I0[2]))
```
This prints
> EllipticFunctions error: -1.1335784726810933e-33
Estimated quadratue error: 1.7795713073256455e-78

Comparison with `ellipf(phi,m)` from mpmath shows that the quadrature result is accurate.

**Comment by simonp0420** [comment] 2022-10-26 16:22
It is known that only a small portion of the code base has been checked to be generic enough to support accurate multiprecision results.  IMO it will likely require a substantial PR to accomplish this.  I'm not anticipating having time to look at this in the foreseeable near term.  @stla, your thoughts?

**Comment by stla** [comment] 2022-10-26 18:47
`ellipticF` is evaluated from `CarlsonRF` whose algorithm stops when some precision is achieved, defined by a small `epsilon`. Maybe reducing this `epsilon` would improve the result. The problem is that in some cases, a too small `epsilon` yields an infinite loop.

**Comment by simonp0420** [comment] 2022-10-27 01:31
I took a look at `CarlsonRF` and it was pretty easy to make it fully generic for extended precision types (See PR 10).  So that takes care of this particular problem.  However, more work will be needed to ensure that all other functions exported by this package also fully support extended precision.  I created Issue #11 as a reminder on this topic.

**Comment by stla** [comment] 2022-11-19 15:18
Thanks. Commit merged.

**Closed as completed by stla** 2022-11-19 15:18 UTC
